# Generated by Django 4.0 on 2021-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('memberNumber', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=10)),
            ],
        ),
    ]
